# Setup
title:        El Maven
tagline:      An opensource LC-MS data processing engine 
baseurl:      "https://sabsgeo.github.io"
paginate:     1

# About/contact
author:
  name:       Sabu George
  url:        https://elucidata.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
