# Setup
title:        El Maven
tagline:      An opensource LC-MS data processing engine 
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Elucidata
  url:        http://elucidata.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
